"""extend_progress_tracking

Revision ID: 20260409115433
Revises: 20260409102525
Create Date: 2026-04-09 11:54:34.530544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260409115433'
down_revision: Union[str, None] = '20260409102525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_course_progress', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('employee_course_progress', sa.Column('completed_lessons', sa.JSON(), nullable=True))
    op.add_column('employee_course_progress', sa.Column('total_time_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_course_progress', 'total_time_seconds')
    op.drop_column('employee_course_progress', 'completed_lessons')
    op.drop_column('employee_course_progress', 'started_at')
    # ### end Alembic commands ###
