"""create_inital_tables

Revision ID: 20260408135235
Revises: 
Create Date: 2026-04-08 13:52:35.761508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260408135235'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_ai_audit_log_timestamp'), 'ai_audit_log', ['timestamp'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leads',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.Integer(), nullable=True),
    sa.Column('expected_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('stage_age_days', sa.Integer(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('total_emails', sa.Integer(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('total_meetings', sa.Integer(), nullable=True),
    sa.Column('last_activity_days_ago', sa.Integer(), nullable=True),
    sa.Column('is_won', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('lms_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_hash', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_audit_log_employee_id'), 'lms_audit_log', ['employee_id'], unique=False)
    op.create_index(op.f('ix_lms_audit_log_timestamp'), 'lms_audit_log', ['timestamp'], unique=False)
    op.create_table('lms_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('material_url', sa.String(length=500), nullable=True),
    sa.Column('ai_generated_summary', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_courses_department'), 'lms_courses', ['department'], unique=False)
    op.create_table('lms_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Enum('level_1', 'level_2', 'level_3', name='tracklevel'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_tracks_department'), 'lms_tracks', ['department'], unique=False)
    op.create_table('upload_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('total_leads', sa.Integer(), nullable=True),
    sa.Column('hot_count', sa.Integer(), nullable=True),
    sa.Column('warm_count', sa.Integer(), nullable=True),
    sa.Column('cold_count', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=True),
    sa.Column('activity_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activities_lead_id'), 'activities', ['lead_id'], unique=False)
    op.create_table('ai_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'executed', 'failed', name='actionstatus'), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_ai_actions_lead_id'), 'ai_actions', ['lead_id'], unique=False)
    op.create_table('ai_lead_scores',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('features_snapshot', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_ai_lead_scores_lead_id'), 'ai_lead_scores', ['lead_id'], unique=False)
    op.create_table('lms_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['lms_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_table('lms_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=200), nullable=False),
    sa.Column('employee_email', sa.String(length=200), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('cert_url', sa.String(length=500), nullable=True),
    sa.Column('cert_serial', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['lms_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_serial')
    )
    op.create_index(op.f('ix_lms_certificates_employee_id'), 'lms_certificates', ['employee_id'], unique=False)
    op.create_table('lms_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=200), nullable=False),
    sa.Column('employee_email', sa.String(length=200), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'paused', name='enrollmentstatus'), nullable=True),
    sa.Column('current_course_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['lms_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_enrollments_employee_id'), 'lms_enrollments', ['employee_id'], unique=False)
    op.create_table('lms_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_track_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['lms_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'course_id', name='uq_track_course')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_notes_lead_id'), 'notes', ['lead_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_opportunities_lead_id'), 'opportunities', ['lead_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'employee', name='roleenum'), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_approvals',
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=200), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['ai_actions.action_id'], ),
    sa.PrimaryKeyConstraint('approval_id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('material_url', sa.String(length=500), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_employee_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=200), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['lms_badges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'badge_id', name='uq_emp_badge')
    )
    op.create_index(op.f('ix_lms_employee_badges_employee_id'), 'lms_employee_badges', ['employee_id'], unique=False)
    op.create_table('lms_quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer_hash', sa.String(length=256), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['lms_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_quiz_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('standard', 'conversational', name='quizmode'), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_hash', sa.String(length=100), nullable=True),
    sa.Column('session_fingerprint', sa.String(length=300), nullable=True),
    sa.Column('tab_switch_count', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['lms_enrollments.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['lms_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_quiz_sessions_enrollment_id'), 'lms_quiz_sessions', ['enrollment_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('lessons', sa.JSON(), nullable=False),
    sa.Column('quiz_questions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_conv_quiz_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_question', sa.Boolean(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['lms_quiz_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_conv_quiz_messages_session_id'), 'lms_conv_quiz_messages', ['session_id'], unique=False)
    op.create_table('lms_quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['lms_quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lms_quiz_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_quiz_attempts_session_id'), 'lms_quiz_attempts', ['session_id'], unique=False)
    op.create_table('employee_course_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='progressstatus'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('chat_history', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'course_id', name='uq_emp_course')
    )
    # ### end Alembic commands ###

    # Generate password hash and inject default super admin using raw SQL wrapper
    import uuid
    import datetime

    admin_id = uuid.uuid4()
    hashed_pwd = "$2b$12$TiHWgwe4beVdTp9J4U7gUusiTwwoEnC2i8wAzGopFKi0Sl6fOLR3C"
    now = datetime.datetime.utcnow()

    op.execute(
        f"INSERT INTO users (id, email, password_hash, role, full_name, created_at, is_active) "
        f"VALUES ('{admin_id}', 'superadmin@utiliko.com', '{hashed_pwd}', 'super_admin', 'System Super Admin', '{now}', true)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_course_progress')
    op.drop_index(op.f('ix_lms_quiz_attempts_session_id'), table_name='lms_quiz_attempts')
    op.drop_table('lms_quiz_attempts')
    op.drop_index(op.f('ix_lms_conv_quiz_messages_session_id'), table_name='lms_conv_quiz_messages')
    op.drop_table('lms_conv_quiz_messages')
    op.drop_table('courses')
    op.drop_index(op.f('ix_lms_quiz_sessions_enrollment_id'), table_name='lms_quiz_sessions')
    op.drop_table('lms_quiz_sessions')
    op.drop_table('lms_quiz_questions')
    op.drop_index(op.f('ix_lms_employee_badges_employee_id'), table_name='lms_employee_badges')
    op.drop_table('lms_employee_badges')
    op.drop_table('documents')
    op.drop_table('ai_approvals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_opportunities_lead_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_notes_lead_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_table('lms_track_courses')
    op.drop_table('lms_modules')
    op.drop_index(op.f('ix_lms_enrollments_employee_id'), table_name='lms_enrollments')
    op.drop_table('lms_enrollments')
    op.drop_index(op.f('ix_lms_certificates_employee_id'), table_name='lms_certificates')
    op.drop_table('lms_certificates')
    op.drop_table('lms_badges')
    op.drop_index(op.f('ix_ai_lead_scores_lead_id'), table_name='ai_lead_scores')
    op.drop_table('ai_lead_scores')
    op.drop_index(op.f('ix_ai_actions_lead_id'), table_name='ai_actions')
    op.drop_table('ai_actions')
    op.drop_index(op.f('ix_activities_lead_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('upload_records')
    op.drop_index(op.f('ix_lms_tracks_department'), table_name='lms_tracks')
    op.drop_table('lms_tracks')
    op.drop_index(op.f('ix_lms_courses_department'), table_name='lms_courses')
    op.drop_table('lms_courses')
    op.drop_index(op.f('ix_lms_audit_log_timestamp'), table_name='lms_audit_log')
    op.drop_index(op.f('ix_lms_audit_log_employee_id'), table_name='lms_audit_log')
    op.drop_table('lms_audit_log')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('departments')
    op.drop_index(op.f('ix_ai_audit_log_timestamp'), table_name='ai_audit_log')
    op.drop_table('ai_audit_log')
    # ### end Alembic commands ###
