"""granular_tracking_v2

Revision ID: 20260410082542
Revises: 20260409115433
Create Date: 2026-04-10 08:25:42.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260410082542'
down_revision: Union[str, None] = '20260409115433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_course_progress', sa.Column('lessons_viewed', sa.JSON(), nullable=True, server_default='[]'))
    op.add_column('employee_course_progress', sa.Column('correct_answers_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('employee_course_progress', sa.Column('total_questions_asked', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('employee_course_progress', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_course_progress', 'updated_at')
    op.drop_column('employee_course_progress', 'total_questions_asked')
    op.drop_column('employee_course_progress', 'correct_answers_count')
    op.drop_column('employee_course_progress', 'lessons_viewed')
    # ### end Alembic commands ###
